FROM grafana/grafana-oss:latest

# Variáveis fixas
ENV GF_ANALYTICS_REPORTING_ENABLED=false \
    
    GF_LOG_FILTERS="migrator:error,sqlstore:error,provisioning:error,plugin:error,settings:error"

# Porta padrão
EXPOSE 3000
