FROM grafana/grafana-oss:latest

# Variáveis fixas
ENV GF_ANALYTICS_REPORTING_ENABLED=false \
    GF_ANALYTICS_CHECK_FOR_UPDATES=false \
    GF_CHECK_FOR_UPDATES=false \
    GRAFANA_SA_NAME=default_sa \
    GRAFANA_TOKEN_NAME=default_token \
    GF_SERVER_HTTP_PORT=3000 \
    GF_SERVER_DOMAIN=localhost \
    GF_USERS_ALLOW_SIGN_UP=false \
    GRAFANA_PUBLIC_TOKEN=36caa442de9549bcb5dfc50a34e7742e \
    GRAFANA_URL=http://grafana:3000 \
    GF_SECURITY_ALLOW_EMBEDDING=true \
    GF_AUTH_ANONYMOUS_ENABLED=true \
    GF_AUTH_ANONYMOUS_ORG_NAME="Main Org." \
    GF_AUTH_ANONYMOUS_ROLE=Viewer \
    GF_FEATURE_TOGGLES_ENABLE=publicDashboards \
    GF_DATABASE_TYPE=postgres \
    GF_DATABASE_SSL_MODE=disable
     # Logging minimalista
      GF_LOG_LEVEL: error
      GF_LOG_MODE: console

      # Desabilitar logs de inicialização
      GF_LOG_FILTERS: >-
        migrator:error,
        sqlstore:error,
        provisioning:error,
        plugin:error,
        settings:error

# Porta padrão
EXPOSE 3000
